# Generated by Django 4.2 on 2023-04-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("haru", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="create_date",
            field=models.DateField(),
        ),
    ]
