# Generated by Django 4.2 on 2023-04-18 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("haru", "0002_alter_diary_create_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_diary",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
