# Generated by Django 4.2 on 2023-04-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("haru", "0003_diary_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="angry",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="diary",
            name="disgust",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="diary",
            name="fear",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="diary",
            name="happiness",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="diary",
            name="neutral",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="diary",
            name="sadness",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="diary",
            name="surprise",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
