# Generated by Django 4.2 on 2023-04-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("haru", "0004_diary_angry_diary_disgust_diary_fear_diary_happiness_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="primary_emotion",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="diary",
            name="secondary_emotion",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
