# Generated by Django 4.2 on 2023-04-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("haru", "0005_diary_primary_emotion_diary_secondary_emotion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emoji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(blank=True, upload_to="emoji/images")),
            ],
        ),
    ]
