# Generated by Django 4.2 on 2023-04-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("haru", "0006_emoji"),
    ]

    operations = [
        migrations.AddField(
            model_name="emoji",
            name="emotion",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
